version: '2'

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.1.0/24

services:
    workspace_node_dev:
#        environment:
#          - PORT=8080
        networks:
          default:
            ipv4_address: 172.20.1.180

    workspace_node_prod:
#        environment:
#          - PORT=80
        networks:
          default:
            ipv4_address: 172.20.1.183

    sshd:
        networks:
          default:
            ipv4_address: 172.20.1.122
